package com.sample
 
import com.sample.Pessoa;
import com.sample.Comida;

rule "Permite crédito"
    when
    
    	$c : Comida()
        $p : Pessoa(idade >= 18, comidaPref == $c.getComida(), $c.getCalorias() <= 500, $p.getRendimento() >= 1000)
    then
        System.out.println("Pessoa maior de idade, com alimentação saudável, rendimento acima do limiar 1000." +
        " Crédito permitido para " + $p.getNome() );
end

rule "Crédito negado"
    when
        Pessoa( $nome : nome, idade < 18)
    then
        System.out.println("Crédito negado para " + $nome);
end

rule "Nega crédito 2"
	when
		$c : Comida()
		$p : Pessoa(idade >= 18, comidaPref == $c.getComida(), $c.getCalorias() >= 500)
	then
		System.out.println("Pessoa maior de idade, com alimentação não saudável." +
		" Crédito negado para " + $p.getNome());
end

rule "Nega crédito 3"
	when
		$c : Comida()
		$p : Pessoa(idade >= 18, comidaPref == $c.getComida(), $c.getCalorias() <= 500, $p.getRendimento() < 1000)
	then
		System.out.println("Pessoa maior de idade, com alimentação saudável, mas sem rendimento mínimo." +
		" Crédito negado para " + $p.getNome());
end

rule "Não sabe"
	when
		$p : Pessoa($nome: nome, idade >= 18)
		forall($c : Comida(comida != $p.getComidaPref()))
	then
		System.out.println("Informação insuficiente sobre alimentação de " + $nome);
end